---
# 
# @author Jason Williams
# Security Directory Integrator v7.2 fix pack installation
# Playbook built using SDI 7.2.0 and Red Hat 8.5

- name: Play SDI - Install SDI Fixpack and JVM Update
# Playbook built using SDI 7.2.0-ISS-SDI-FP0008 and IBM JVM 8.0.6.25

# Hosts where the Security Directory Integrator V7.2(SDI) product is installed
  hosts: iam_sdi_hosts
  strategy: free
  vars_files:
    - variables.yml 
  become_user: root
  become: true
  
  tasks:
  # Collect JVM Version
    - name: Collect {{ sdi_root_dir }}/jvm/jre/bin/java version
      shell: > 
          ./jvm/jre/bin/java
          -fullversion
      args:
        chdir: {{ sdi_root_dir }}
      register: java_version

  # Collect SDI Version
    - name: Check {{ sdi_root_dir }} version
      shell: > 
          ./bin/applyUpdates.sh
          -queryreg
      args:
        chdir: {{ sdi_root_dir }}
      register: sdi_version      

  # Collection results
    - name: Print version information 
      vars: 
        msg: |
            Host: {{ ansible_fqdn }}
            SDI Version: {{ sdi_version }}
            SDI JVM Version: {{ java_version }}
      debug: 
        msg: "{{ msg.split('\n') }}"       
...