# 
# @author Jason Williams
# Security Directory Integrator v7.2 Installation
# Playbook built using SDI 7.2.0 and Red Hat 8.5

- name: Play SDI - Install Security Directory Integrator
# HOST SYSTEMS
  hosts: iam_sdi_hosts
  strategy: free 
  vars_files:
    - variables.yml 
  become_user: root
  become: true

  tasks:
    - name: Create temporary build directory
      ansible.builtin.tempfile:
        state: directory
        suffix: build
      register: tempdir

  # INSTALL OS PREREG
    - name: Install a list of OS packages
      yum:
        name:
          - glibc
          - nss-softokn
          - libXpm
          - libXtst
          - gtk2
          - libcanberra-gtk2
          - dejavu-lgc-sans-fonts
        state: present 
      when: ( ansible_distribution == "RedHat" and ansible_distribution_major_version == | int >= 7 ) or 
            ( ansible_distribution == "CentOS" and ansible_distribution_major_version == | int >= 7 ) 

    - name: Update all OS packages 
      yum: name=* state=latest
      when: ansible_os_family == "RedHat"
      #when: ansible_distribution == 'RedHat'

  # INSTALL SDI PRODUCT
    - name: Extrace SDI Installer to temp directory 
      ansible.builtin.unarchive:
        src: install_images/SDI_7.2_XLIN86_64_ML.tar
        dest: '{{ tempdir.path }}'

    - name: Copy silent install property file to host
      copy:
        src: install_images/CustomInstallRspSDI72.txt
        dest: '{{ tempdir.path }}'

    - name: Update install directory in silent property file
      ansible.builtin.lineinfile:
        path: '{{ tempdir.path }}/CustomInstallRspSDI72.txt'
        regexp: 'USER_INSTALL_DIR'
        line: 'USER_INSTALL_DIR={{ sdi_root_dir }}'

    - name: Update solution directory in silent property file
      ansible.builtin.lineinfile:
        path: '{{ tempdir.path }}/CustomInstallRspSDI72.txt'
        regexp: 'TDI_SELECTED_SOLDIR'
        line: 'TDI_SELECTED_SOLDIR={{ sdi_solution_directory }}'

    - name : Install SDI product
      shell: > 
          ./install_sdiv72_linux_x86_64.bin
          -f '{{ tempdir.path }}/CustomInstallRspSDI72.txt'
          -D\$TDI_SKIP_VERSION_CHECK\$='true'
          -D\$TDI_NOSHORTCUTS\$='true'
          -i silent
      args:
        chdir: '{{ tempdir.path }}/linux_x86_64'
      register: diff_cmd
      failed_when: diff_cmd.rc == 0 or diff_cmd.rc >= 2

  # REMOVE TEMP DIRECTORY
    - name: Remove the registered tempdir directory
      ansible.builtin.file:
        path: "{{ tempdir.path }}"
        state: absent
      when: tempdir.path is defined
...
