---
# 
# @author Jason Williams
# ISIM Dispatcher - Installation
# Playbook built using SDI 7.2.0 and Red Hat 8.5
- name: Play ISIM Dispatcher - Install ISIM Dispatcher
# Playbook built using SDI 7.2.0-ISS-SDI-FP0008 and IBM JVM 8.0.6.25

# Hosts where the Security Directory Integrator V7.2(SDI) product is installed
  hosts: iam_sdi_hosts
  strategy: free
  vars_files:
    - variables.yml 
  become_user: root
  become: true

  tasks:
    - name: Create temporary build directory
      ansible.builtin.tempfile:
        state: directory
        suffix: build
      register: tempdir

  # KILL ALL SDI PROCESS
    - name: Prompt user to acknowledge the shutdown of the SDI Server.
      pause:
        prompt: By continuing the SDI Server process will be terminated on host. 

    - name: Get running processes list from remote host
      ignore_errors: yes
      shell: "ps -few | grep {{ sdi_root_dir }} | grep -v grep | awk '{print $2}'"
      register: running_processes

    - name: Kill running processes
      ignore_errors: yes
      shell: "kill {{ item }}"
      with_items: "{{ running_processes.stdout_lines }}"

    - name: Force kill stuck processes
      ignore_errors: yes
      shell: "kill -9 {{ item }}"
      with_items: "{{ running_processes.results | select('failed') | map(attribute='item') | list }}"

  # EXTRACT DISPATCHER PACKAGE
    - name: Extract Dispatcher 
      unarchive:
        src: install_images/SIA_RMI_7140_SDI_7X_MP_ML.zip
        dest: '{{ tempdir.path }}'

    - name: Install ISIM Dispatcher product
      shell: >
          {{ sdi_root_dir }}/jvm/jre/bin/java
          -jar {{ tempdir.path }}/DispatcherInstall.jar
          -i silent -DUSER_INSTALL_DIR={{ sdi_root_dir }}
          -DUSER_SELECTED_SOLDIR={{ sdi_root_dir }}/timsol
          -DUSER_INPUT_RMI_PORTNUMBER=1199
          -DUSER_INPUT_WS_PORTNUMBER=8081
          -DUSER_SYSQUEUE_USERNAME_INPUT_RESULT=disp_user
          -DUSER_SYSQUEUE_PASSWORD_INPUT_RESULT=admin@123
          -DUSER_SYSQUEUE_REPASSWORD_INPUT_RESULT=admin@123
          -DUSER_INPUT_RESULTS_FOR_SSL=Enable
      args:
        chdir: '{{ tempdir.path }}'
  #    register: diff_cmd
  #    failed_when: diff_cmd.rc == 0 or diff_cmd.rc >= 2

  # INSTALL ISIM DISPATCHER
    - name: Pause playbook for 3 seconds 
      pause:
        seconds: 3

    - name: Insert/Update TLS properties in {{ sdi }}/etc/global.properties
      blockinfile:
        path: '{{ sdi_root_dir }}/timsol/solution.properties'
        backup: yes
        marker: "## <!-- {mark} ANSIBLE MANAGED BLOCK -->"
        block: |
          # # ---------------------------------- 
          # # Protocols to enforce SSL protocols in a SDI Server 
          # # Optional values for com.ibm.di.SSL* property (TLSv1, TLSv1.1, TLSv1.2). 
          # # This can be a multi-valued comma separated property. 
          # # Optional values for com.ibm.jsse2.overrideDefaultProtocol property (SSL_TLSv2, TLSv1, 
          # # TLSv11,TLSv12). This is a single value property.
          # # ---------------------------------- 
          com.ibm.di.SSLProtocols=TLSv1.2
          com.ibm.di.SSLServerProtocols=TLSv1.2 
          com.ibm.jsse2.overrideDefaultProtocol=TLSv12 
          com.ibm.jsse2.overrideDefaultTLS=true
          # # ----- ----------------------------- 
          # # Protocols used for built-in SDI Server web container traffic. 
          # # This effects the web.server.port property 
          # # URLs used by the web.server.port property are
          # # e.g. 
          # # https://localhost:1098/dashboard 
          # # https://localhost:1098/sdi 
          # # https://localhost:1098/rest 
          # # ---------------------------------- 
          org.eclipse.equinox.http.jetty.ssl.protocol=TLSv1.2

  # REMOVE TEMP DIRECTORY
    - name: Remove the registered tempdir directory
      ansible.builtin.file:
        path: "{{ tempdir.path }}"
        state: absent
      when: tempdir.path is defined
...
