---
# 
# @author Jason Williams
# Security Directory Integrator v7.2 Installation
# Playbook built using SDI 7.2.0 and Red Hat 8.5

- name: Play SDI - Install SDI Fixpack and JVM Update
# Hosts where the Security Directory Integrator V7.2(SDI) product is installed
  hosts: iam_sdi_hosts
  vars_files:
    - variables.yml 
  become_user: root
  become: true

  tasks:
    - name: Create temp working directory
      file:
        path: '{{ temp }}'
        state: directory

  # INSTALLING JVM UPDATE
    - name: Backup {{ sdi_root_dir }}/jvm
      command: mv '{{ sdi_root_dir}}/jvm' '{{ sdi_root_dir}}/jvm.backup.'{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}

    - name: Extrace JVM Update 
      unarchive:
        src: install_images/SDI/ibm-java-jre-8.0-6.25-linux-x86_64.tgz
        dest: '{{ sdi_root_dir}}'

    - name: Prepare the {{ sdi_root_dir }}/jvm directory 
      file: 
        path: '{{ sdi_root_dir }}/jvm'
        state: absent 

    - name: Apply ibm-java to the {{ sdi_root_dir }}/jvm directory
      command: mv '{{ sdi_root_dir}}/ibm-java-x86_64-80' '{{ sdi_root_dir}}/jvm'

    - name: Update port in java.policy file to fix Derby
      # Java.policy must be update to allow Derby to properly start
      lineinfile: 
        path: '{{ sdi_root_dir }}/jvm/jre/lib/security/java.policy'
        # The String to Search
        regexp: "localhost" 
        # The String to Replace
        line: '        permission java.net.SocketPermission "localhost:${derby.drda.portNumber}", "listen";' 
        state: present
        backup: yes

    - name: Add deregisterDriver in java.policy file to fix Derby
      lineinfile:
        path: '{{ sdi_root_dir }}/jvm/jre/lib/security/java.policy'
        insertafter: 'localhost'
        line: '        permission java.sql.SQLPermission "deregisterDriver", "";'
        firstmatch: yes 
        backup: yes

  # INSTALLING SDI FIXPACK 
    - name: Extract fix pack into {{ temp }}
      unarchive:
        src: install_images/SDI/7.2.0-ISS-SDI-FP0008.zip
        dest: '{{ temp }}'

    - name: Remove previous UpdateInstaller.jar
      file:
        path: '{{ sdi_root_dir}}/maintenance/UpdateInstaller.jar'
        state: absent

    - name: Applying 7.2.0-ISS-SDI-FP0008
      command: "{{ item }} chdir={{ sdi_root_dir }}/"
      with_items:
      - mv {{ temp }}/7.2.0-ISS-SDI-FP0008/7.2.0-ISS-SDI-FP0008/UpdateInstaller.jar maintenance/UpdateInstaller.jar
      - ./bin/applyUpdates.sh -update {{ temp }}/7.2.0-ISS-SDI-FP0008/7.2.0-ISS-SDI-FP0008/SDI-7.2-FP0008.zip
      - chmod 744 ./bin/updateLog4j.sh ./bin/removeAMC.sh
      - ./bin/updateLog4j.sh
      - ./bin/removeAMC.sh

  # REMOVE TEMP DIRECTORY
    - name: Remove temp working directory
      file:
        path: '{{ temp }}' 
        state: absent

  # UPDATE GLOBAL PROPERTIES
    - name: Insert/Update TLS properties in {{ sdi }}/etc/global.properties
      blockinfile:
        path: '{{ sdi_root_dir }}/etc/global.properties'
        backup: yes
        marker: "## <!-- {mark} ANSIBLE MANAGED BLOCK -->"
        block: |
          # # ---------------------------------- 
          # # Protocols to enforce SSL protocols in a SDI Server 
          # # Optional values for com.ibm.di.SSL* property (TLSv1, TLSv1.1, TLSv1.2). 
          # # This can be a multi-valued comma separated property. 
          # # Optional values for com.ibm.jsse2.overrideDefaultProtocol property (SSL_TLSv2, TLSv1, 
          # # TLSv11,TLSv12). This is a single value property.
          # # ---------------------------------- 
          com.ibm.di.SSLProtocols=TLSv1.2 
          com.ibm.di.SSLServerProtocols=TLSv1.2 
          com.ibm.jsse2.overrideDefaultProtocol=TLSv12 
          com.ibm.jsse2.overrideDefaultTLS=true
          # # ----- ----------------------------- 
          # # Protocols used for built-in SDI Server web container traffic. 
          # # This effects the web.server.port property 
          # # URLs used by the web.server.port property are
          # # e.g. 
          # # https://localhost:1098/dashboard 
          # # https://localhost:1098/sdi 
          # # https://localhost:1098/rest 
          # # ---------------------------------- 
          org.eclipse.equinox.http.jetty.ssl.protocol=TLSv1.2

...