---
# 
# @author Jason Williams
# Security Directory Integrator v7.2 - Manually Uninstall the product
# NOTE: This removes the registry for ALL installations of SDI or TDI on the host
# Playbook built using SDI 7.2.0 and Red Hat 8.5

- name: Play SDI - Remove Security Directory Integrator
# Hosts where SDI product is installed
  hosts: iam_sdi_hosts
  vars_files:
    - variables.yml
  become_user: root
  become: true

  tasks:
  # KILL ALL SDI PROCESS
    - name: Get running processes list from remote host
      ignore_errors: yes
      shell: "ps -few | grep {{ sdi_root_dir }} | grep -v grep | awk '{print $2}'"
      register: running_processes

    - name: Kill running processes
      ignore_errors: yes
      shell: "kill {{ item }}"
      with_items: "{{ running_processes.stdout_lines }}"

    - name: Force kill stuck processes
      ignore_errors: yes
      shell: "kill -9 {{ item }}"
      with_items: "{{ running_processes.results | select('failed') | map(attribute='item') | list }}"

  # MANUALLY REMOVE PRODUCT
    - name: Delete SDI from system
      file:
        path: '{{ item }}'
        state: absent
      with_items:
        - '{{ sdi_root_dir }}'
        - /var/.com.zerog.registry.xml
...