---
# 
# @author Jason Williams
# Security Directory Integrator v7.2 - Manually Uninstall the product
# NOTE: This removes the registry for ALL installations of SDI or TDI on the host
# Playbook built using SDI 7.2.0 and Red Hat 8.5

- name: Play SDI - Remove Security Directory Integrator
# Hosts where SDI product is installed
  hosts: iam_sdi_hosts
  vars_files:
    - variables.yml
  become_user: root
  become: true

  tasks:
    - name: Delete SDI from system
      file:
        path: '{{ item }}'
        state: absent
      with_items:
        - '{{ sdi_root_dir }}'
        - /var/.com.zerog.registry.xml
...