# Workaround for CVE-2020-27216 (Jetty - Dashboard)

# Create a temporary work folder which is not writable by everybody, but is readable/writable by the SDI server
    - name: modify ownership & permissions of a directory
      file:
        path: '{{ sdi_root_dir }}/dashboard_tmpdir'
        state: directory
#        owner: "{{ ansible_user }}"
#        group: "{{ ansible_user }}"
        mode: 0700

# java.io.tmpdir in solution.properties to the name of this temporary work folder.
    - name: Insert/Update CVE-2020-27216 workaround in {{ sdi_root_dir }}/etc/global.properties
      blockinfile:
        path: '{{ sdi_root_dir }}/etc/global.properties'
        backup: yes
        marker: "## <!-- {mark} ANSIBLE MANAGED BLOCK - CVE-2020-27216 -->"
        block: |
          # # ----------------------------------
          # # Workaround for CVE-2020-27216 (Jetty - Dashboard)
          # # ----------------------------------
          java.io.tmpdir={{ sdi_root_dir }}/dashboard_tmpdir

